name = "discord-userdoccers"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[unsafe.bindings]]
name = "ERROR_CODES_RATELIMIT"
type = "rate_limit"
namespace_id = "1337"

simple = { limit = 5, period = 60 }
